Sc 3855/looker run query and download as file
shipyardapp/looker-blueprints pull request #1
Opened 2022-07-18 21:58 UTC by Shamwayne

2022-07-22 15:59 UTC, smjohnsonShipyard requested changes

2022-07-22 15:59 UTC, smjohnsonShipyard commented on looker_blueprints/run_query_and_download.py
> +    parser.add_argument('--query-id', dest='query_id', required=False)
query-id should be required. Also file_type, dest_file_name, dest_file_folder should be arguments here.

2022-08-23 03:03 UTC, ericelsken requested changes

2022-08-23 03:03 UTC, ericelsken commented on looker_blueprints/run_query_and_download.py
> +        print("query {new_query.id} created successfully")
Looks like `new_query` doesn't exist and this isn't an f-string.

2022-08-23 03:03 UTC, ericelsken commented on looker_blueprints/run_query_and_download.py
> +                        choices=['json', 'json_detail','csv', 'html', 'xlsx', 'md', 'sql' ,'png', 'jpg'],
Formatting is off.

2022-08-23 03:03 UTC, ericelsken commented on looker_blueprints/helpers.py
> +        config["client_secret"] = self.client_secret
Make the use of single and double quotes consistent.

2022-11-21 15:53 UTC, closed without merging