Sc 3856/looker create query
shipyardapp/looker-blueprints pull request #4
Opened 2022-07-18 22:07 UTC by Shamwayne

2022-07-22 15:34 UTC, smjohnsonShipyard commented
@Shamwayne I'm not seeing where I can input a query to be created. Could you help me understand what you were expecting a user to submit for the filters argument?

2022-08-10 15:51 UTC, Shamwayne commented
The filter segment of the code acts as the body containing the query/filter query that needs to be executed

2022-08-23 03:11 UTC, ericelsken requested changes

2022-08-23 03:11 UTC, ericelsken commented on looker_blueprints/create_query.py
> +        sys.exit(EXIT_CODE_LOOK_QUERY_ERROR)
Make string quotes consistent. Needs to be a format-string.

2022-11-21 15:53 UTC, closed without merging